name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

# Cancel in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        cache: true
    
    - name: Get current dependencies
      run: flutter pub get
    
    - name: Update dependencies
      run: flutter pub upgrade
    
    - name: Run tests after update
      run: flutter test
      continue-on-error: true
    
    - name: Check if pubspec.lock changed
      id: changes
      run: |
        if git diff --quiet pubspec.lock; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Pull Request
      if: steps.changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Flutter dependencies'
        title: 'chore: Update Flutter dependencies'
        body: |
          ## Automated Dependency Update
          
          This PR updates Flutter dependencies to their latest compatible versions.
          
          ### Changes
          - Updated pubspec.lock with latest dependency versions
          
          ### Testing
          - ✅ All tests passed after dependency update
          - ✅ Code analysis completed successfully
          
          Please review the changes and merge if everything looks good.
          
          Generated by GitHub Actions 🤖
        branch: chore/update-dependencies
        delete-branch: true

  check-flutter-version:
    name: Check Flutter Version
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get current Flutter version
      run: |
        CURRENT_VERSION="3.27.0"
        echo "Current version: $CURRENT_VERSION"
        
        # Check latest stable version (this is a simplified check)
        echo "Checking for newer Flutter versions..."
        echo "Please manually update the Flutter version in workflows if needed."
